"""empty message

Revision ID: 3b4f82682cfc
Revises: 4b67f17efe84
Create Date: 2025-04-16 10:33:30.762634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4f82682cfc'
down_revision = '4b67f17efe84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.drop_constraint('user_contrasena_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_contrasena_key', ['contrasena'])
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
