"""empty message

Revision ID: 4b67f17efe84
Revises: f6bdf22ec7fd
Create Date: 2025-04-16 10:10:05.981373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b67f17efe84'
down_revision = 'f6bdf22ec7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('simbolo', sa.String(length=120), nullable=False),
    sa.Column('tasa_cambio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billetera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('valor_total', sa.Integer(), nullable=False),
    sa.Column('divisa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['divisa_id'], ['divisa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('billetera_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'billetera', ['billetera_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('billetera_id')
        batch_op.drop_column('categoria_id')

    op.drop_table('billetera')
    op.drop_table('divisa')
    # ### end Alembic commands ###
