"""empty message

Revision ID: 656d43923546
Revises: ab11f7bdbd8b
Create Date: 2025-04-18 11:53:29.751182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656d43923546'
down_revision = 'ab11f7bdbd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
