"""empty message

Revision ID: f7a2212349df
Revises: ebc2118de2b8
Create Date: 2025-04-16 05:34:20.378489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a2212349df'
down_revision = 'ebc2118de2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fecha_login', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['contrasena'])
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_login')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('nombre')
        batch_op.drop_column('contrasena')

    op.drop_table('registro')
    # ### end Alembic commands ###
